name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Build with dotnet
        run: dotnet build -c Release
      - name: Setup minio
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          mkdir -p ~/minio/data

          docker run \
          -p 9000:9000 \
          -p 9090:9090 \
          --name minio \
          -v ~/minio/data:/data \
          -e "MINIO_ROOT_USER=ROOTUSER" \
          -e "MINIO_ROOT_PASSWORD=ChangeMe123" \
          quay.io/minio/minio server /data --console-address ":9090"
      - name: Run tests with coverage
        if: startsWith(matrix.os, 'ubuntu')
        env:
          GITHUB: true
        run: |
          cd ./src/Storage.Tests/
          dotnet test -c Release --no-build /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=opencover /p:Exclude="[*]Storage.Benchmark.*"
      - name: Publish coverage report
        if: startsWith(matrix.os, 'ubuntu')
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
